app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: "PT10M"
    force-check-delay: "PT60M"
  github-base-url:
    base-url: "https://api.github.com/repos/"
  stackoverflow-base-url:
    base-url: "https://api.stackexchange.com/2.3/questions/"
  bot-base-url:
    base-url: "http://localhost:8090"
  use-queue: true

api:
  bot:
    retry-policy: constant
    attempts: 3
    http-statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
    interval: 5000

spring:
  application:
    name: scrapper
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper

management:
  server:
    port: 8081
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,health,prometheus"
      path-mapping:
        prometheus: "metrics"

kafka:
  topic: "messages.updates"
  bootstrap-servers: localhost:29091
  replication-factor: 1
  partitions: 2
  acks-mode: all
  delivery-timeout: 60_000
  batch-size: 100_000
  enable-idempotence: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  count: 10
