app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
  github-base-url:
    base-url: "https://api.github.com/repos/"
  stackoverflow-base-url:
    base-url: "https://api.stackexchange.com/2.3/questions/"
  bot-base-url:
    base-url: "http://localhost:8090"

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/scrapper"
    username: ${LOGIN}
    password: ${PASSWORD}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
