app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-base-url:
    base-url: "http://localhost:8080"
  scrapper-topic-name: "messages.updates"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

api:
  scrapper:
    retry-policy: constant
    attempts: 3
    http-statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
    interval: 5000

management:
  server:
    port: 8091
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,health,prometheus"
      path-mapping:
        prometheus: "metrics"

kafka:
  group-id: messages-group
  bootstrap-servers: localhost:29091
  auto-offset-reset: latest
  max-poll-interval-ms: 300_000
  enable-auto-commit: false
  concurrency: 1
  replication-factor: 1
  dlq:
    topic: messages.updates_dlq
    replication-factor: 1
    partitions: 2
    acks-mode: all
    delivery-timeout: 60_000
    batch-size: 100_000

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  count: 10
